projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev:
          url: http://localhost:4000
          subscription:
            url: ws://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
